spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

---

spring:
  profiles: dev

  jpa:
    database: POSTGRESQL
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/db_indonesia
    username: admin
    password: B@ndung123

server:
  port: 8081

  servlet:
    context-path: /v1

---

spring:
  profiles: uat

  jpa:
    database: POSTGRESQL
    show-sql: true

  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/db_indonesia
    username: admin
    password: B@ndung123

server:
  port: 8082
  
  servlet:
    context-path: /v1